"""DANFSe generation helpers for NT 008 SE/CGNFS-e."""

from .html import render_danfse_html, render_header_html
from .models import (
    ComplementaryInfoData,
    CustomerData,
    DanfseData,
    DestinationData,
    FederalTaxationData,
    HeaderData,
    IbsCbsTaxationData,
    IntermediaryData,
    MunicipalTaxationData,
    ProviderData,
    ReceiptData,
    ServiceData,
    TotalData,
)
from .pdf import render_danfse_pdf, render_header_pdf
from .validation import ValidationIssue, validate_danfse_data, validate_layout_constants
from .xml import (
    parse_complementary_info,
    parse_customer,
    parse_danfse,
    parse_destination,
    parse_federal_taxation,
    parse_header,
    parse_ibs_cbs_taxation,
    parse_intermediary,
    parse_municipal_taxation,
    parse_provider,
    parse_receipt,
    parse_service,
    parse_total,
)

__all__ = [
    "ComplementaryInfoData",
    "CustomerData",
    "DanfseData",
    "DestinationData",
    "FederalTaxationData",
    "HeaderData",
    "IbsCbsTaxationData",
    "IntermediaryData",
    "MunicipalTaxationData",
    "ProviderData",
    "ReceiptData",
    "ServiceData",
    "TotalData",
    "ValidationIssue",
    "parse_danfse",
    "parse_complementary_info",
    "parse_customer",
    "parse_destination",
    "parse_federal_taxation",
    "parse_header",
    "parse_ibs_cbs_taxation",
    "parse_intermediary",
    "parse_municipal_taxation",
    "parse_provider",
    "parse_receipt",
    "parse_service",
    "parse_total",
    "render_danfse_html",
    "render_danfse_pdf",
    "render_header_html",
    "render_header_pdf",
    "validate_danfse_data",
    "validate_layout_constants",
]
